/* tslint:disable */
/* eslint-disable */
/**
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s machine translation technology.
 *
 * The version of the OpenAPI document: 2.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentTranslationError
 */
export interface DocumentTranslationError {
    /**
     * detailed error message
     * @type {string}
     * @memberof DocumentTranslationError
     */
    message?: string;
}

/**
 * Check if a given object implements the DocumentTranslationError interface.
 */
export function instanceOfDocumentTranslationError(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DocumentTranslationErrorFromJSON(json: any): DocumentTranslationError {
    return DocumentTranslationErrorFromJSONTyped(json, false);
}

export function DocumentTranslationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentTranslationError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function DocumentTranslationErrorToJSON(value?: DocumentTranslationError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

