/* tslint:disable */
/* eslint-disable */
/**
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s machine translation technology.
 *
 * The version of the OpenAPI document: 2.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The language in which the source texts in the glossary are specified.
 * @export
 */
export const GlossarySourceLanguage = {
  De: 'de',
  En: 'en',
  Es: 'es',
  Fr: 'fr',
  Ja: 'ja',
  It: 'it',
  Pl: 'pl',
  Nl: 'nl',
} as const
export type GlossarySourceLanguage =
  (typeof GlossarySourceLanguage)[keyof typeof GlossarySourceLanguage]

export function GlossarySourceLanguageFromJSON(
  json: any,
): GlossarySourceLanguage {
  return GlossarySourceLanguageFromJSONTyped(json, false)
}

export function GlossarySourceLanguageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GlossarySourceLanguage {
  return json as GlossarySourceLanguage
}

export function GlossarySourceLanguageToJSON(
  value?: GlossarySourceLanguage | null,
): any {
  return value as any
}
