/* tslint:disable */
/* eslint-disable */
/**
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s machine translation technology.
 *
 * The version of the OpenAPI document: 2.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The language in which the target texts in the glossary are specified.
 * @export
 */
export const GlossaryTargetLanguage = {
  De: 'de',
  En: 'en',
  Es: 'es',
  Fr: 'fr',
  Ja: 'ja',
  It: 'it',
  Pl: 'pl',
  Nl: 'nl',
} as const
export type GlossaryTargetLanguage =
  (typeof GlossaryTargetLanguage)[keyof typeof GlossaryTargetLanguage]

export function GlossaryTargetLanguageFromJSON(
  json: any,
): GlossaryTargetLanguage {
  return GlossaryTargetLanguageFromJSONTyped(json, false)
}

export function GlossaryTargetLanguageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GlossaryTargetLanguage {
  return json as GlossaryTargetLanguage
}

export function GlossaryTargetLanguageToJSON(
  value?: GlossaryTargetLanguage | null,
): any {
  return value as any
}
