/* tslint:disable */
/* eslint-disable */
/**
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s machine translation technology.
 *
 * The version of the OpenAPI document: 2.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListGlossaryLanguages400Response
 */
export interface ListGlossaryLanguages400Response {
    /**
     * Generic description of the error.
     * @type {string}
     * @memberof ListGlossaryLanguages400Response
     */
    message?: string;
    /**
     * More specific description of the error.
     * @type {string}
     * @memberof ListGlossaryLanguages400Response
     */
    detail?: string;
}

/**
 * Check if a given object implements the ListGlossaryLanguages400Response interface.
 */
export function instanceOfListGlossaryLanguages400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListGlossaryLanguages400ResponseFromJSON(json: any): ListGlossaryLanguages400Response {
    return ListGlossaryLanguages400ResponseFromJSONTyped(json, false);
}

export function ListGlossaryLanguages400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListGlossaryLanguages400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'detail': !exists(json, 'detail') ? undefined : json['detail'],
    };
}

export function ListGlossaryLanguages400ResponseToJSON(value?: ListGlossaryLanguages400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'detail': value.detail,
    };
}

