/* tslint:disable */
/* eslint-disable */
/**
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s machine translation technology.
 *
 * The version of the OpenAPI document: 2.9.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ListGlossaryLanguages200ResponseSupportedLanguagesInner
 */
export interface ListGlossaryLanguages200ResponseSupportedLanguagesInner {
  /**
   * The language in which the source texts in the glossary are specified.
   * @type {string}
   * @memberof ListGlossaryLanguages200ResponseSupportedLanguagesInner
   */
  sourceLang: string
  /**
   * The language in which the target texts in the glossary are specified.
   * @type {string}
   * @memberof ListGlossaryLanguages200ResponseSupportedLanguagesInner
   */
  targetLang: string
}

/**
 * Check if a given object implements the ListGlossaryLanguages200ResponseSupportedLanguagesInner interface.
 */
export function instanceOfListGlossaryLanguages200ResponseSupportedLanguagesInner(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && 'sourceLang' in value
  isInstance = isInstance && 'targetLang' in value

  return isInstance
}

export function ListGlossaryLanguages200ResponseSupportedLanguagesInnerFromJSON(
  json: any,
): ListGlossaryLanguages200ResponseSupportedLanguagesInner {
  return ListGlossaryLanguages200ResponseSupportedLanguagesInnerFromJSONTyped(
    json,
    false,
  )
}

export function ListGlossaryLanguages200ResponseSupportedLanguagesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListGlossaryLanguages200ResponseSupportedLanguagesInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    sourceLang: json['source_lang'],
    targetLang: json['target_lang'],
  }
}

export function ListGlossaryLanguages200ResponseSupportedLanguagesInnerToJSON(
  value?: ListGlossaryLanguages200ResponseSupportedLanguagesInner | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    source_lang: value.sourceLang,
    target_lang: value.targetLang,
  }
}
