/* tslint:disable */
/* eslint-disable */
/**
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s machine translation technology.
 *
 * The version of the OpenAPI document: 2.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Language of the text to be translated. Options currently available:
 *  * `BG` - Bulgarian
 *  * `CS` - Czech
 *  * `DA` - Danish
 *  * `DE` - German
 *  * `EL` - Greek
 *  * `EN` - English
 *  * `ES` - Spanish
 *  * `ET` - Estonian
 *  * `FI` - Finnish
 *  * `FR` - French
 *  * `HU` - Hungarian
 *  * `ID` - Indonesian
 *  * `IT` - Italian
 *  * `JA` - Japanese
 *  * `KO` - Korean
 *  * `LT` - Lithuanian
 *  * `LV` - Latvian
 *  * `NB` - Norwegian (Bokmål)
 *  * `NL` - Dutch
 *  * `PL` - Polish
 *  * `PT` - Portuguese (all Portuguese varieties mixed)
 *  * `RO` - Romanian
 *  * `RU` - Russian
 *  * `SK` - Slovak
 *  * `SL` - Slovenian
 *  * `SV` - Swedish
 *  * `TR` - Turkish
 *  * `UK` - Ukrainian
 *  * `ZH` - Chinese
 * 
 * If this parameter is omitted, the API will attempt to detect the language of the text and translate it.
 * @export
 */
export const SourceLanguage = {
    Bg: 'BG',
    Cs: 'CS',
    Da: 'DA',
    De: 'DE',
    El: 'EL',
    En: 'EN',
    Es: 'ES',
    Et: 'ET',
    Fi: 'FI',
    Fr: 'FR',
    Hu: 'HU',
    Id: 'ID',
    It: 'IT',
    Ja: 'JA',
    Ko: 'KO',
    Lt: 'LT',
    Lv: 'LV',
    Nb: 'NB',
    Nl: 'NL',
    Pl: 'PL',
    Pt: 'PT',
    Ro: 'RO',
    Ru: 'RU',
    Sk: 'SK',
    Sl: 'SL',
    Sv: 'SV',
    Tr: 'TR',
    Uk: 'UK',
    Zh: 'ZH'
} as const;
export type SourceLanguage = typeof SourceLanguage[keyof typeof SourceLanguage];


export function SourceLanguageFromJSON(json: any): SourceLanguage {
    return SourceLanguageFromJSONTyped(json, false);
}

export function SourceLanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceLanguage {
    return json as SourceLanguage;
}

export function SourceLanguageToJSON(value?: SourceLanguage | null): any {
    return value as any;
}

