/* tslint:disable */
/* eslint-disable */
/**
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s machine translation technology.
 *
 * The version of the OpenAPI document: 2.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TranslateText200ResponseTranslationsInner } from './TranslateText200ResponseTranslationsInner';
import {
    TranslateText200ResponseTranslationsInnerFromJSON,
    TranslateText200ResponseTranslationsInnerFromJSONTyped,
    TranslateText200ResponseTranslationsInnerToJSON,
} from './TranslateText200ResponseTranslationsInner';

/**
 * 
 * @export
 * @interface TranslateText200Response
 */
export interface TranslateText200Response {
    /**
     * 
     * @type {Array<TranslateText200ResponseTranslationsInner>}
     * @memberof TranslateText200Response
     */
    translations?: Array<TranslateText200ResponseTranslationsInner>;
}

/**
 * Check if a given object implements the TranslateText200Response interface.
 */
export function instanceOfTranslateText200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TranslateText200ResponseFromJSON(json: any): TranslateText200Response {
    return TranslateText200ResponseFromJSONTyped(json, false);
}

export function TranslateText200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslateText200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'translations': !exists(json, 'translations') ? undefined : ((json['translations'] as Array<any>).map(TranslateText200ResponseTranslationsInnerFromJSON)),
    };
}

export function TranslateText200ResponseToJSON(value?: TranslateText200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'translations': value.translations === undefined ? undefined : ((value.translations as Array<any>).map(TranslateText200ResponseTranslationsInnerToJSON)),
    };
}

